project:
  type: book

book:
  title: "Google Colab for Neurotechnology"
  author: "Bhargav Kowshik"
  date: "13/05/2026"
  chapters:
    - index.qmd
    - common.qmd
    - neuroai.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



