project:
  type: book

book:
  title: "Google Colab for Neurotechnology"
  author: "Bhargav Kowshik"
  date: "2026-05-13"
  sidebar:
    logo: cover.png
  site-url: https://bkowshik.github.io/google-colab-for-neurotech/
  chapters:
    - index.qmd
    - common.qmd
    - neuroai.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
